name: Client Tests

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9.0.5

      - name: Install dependencies
        run: pnpm install --shamefully-hoist

      - name: Run Lint
        run: pnpm lint:ci
