name: Test deployment

on:
  pull_request:
    branches: [main]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          sparse-checkout: docs
          sparse-checkout-cone-mode: false

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies & Build
        run: |
          yarn install --frozen-lockfile
          yarn build
