name: Test deployment

on:
  workflow_call:

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 9.0.5

      - name: Install dependencies & Build
        run: |
          pnpm install --frozen-lockfile --shamefully-hoist
          pnpm build
