name: Pull Request Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  server-tests:
    name: "Server Tests"
    uses: ./.github/workflows/server-test.yml

  client-tests:
    name: "Client Tests"
    uses: ./.github/workflows/client-test.yml

  docs-tests:
    name: "Docs Tests"
    uses: ./.github/workflows/deploy-docs-test.yml
